import Link from "next/link";
import { CalendarDays, ChevronRight, Flag, MapPin, Radio, Trophy } from "lucide-react";
import { CompetitionCard } from "@/components/race/preview-components";
import { previewClubRankings, previewProgramme } from "@/constants/interface-preview";

const viewNames: Record<string, string> = { inscriptions: "Inscriptions", tirage: "Tirage des séries", qualifications: "Qualifications", parametres: "Paramètres", notifications: "Notifications", menu: "Menu de compétition" };

export default async function CompetitionsPage({ searchParams }: { searchParams: Promise<{ vue?: string }> }) {
  const { vue } = await searchParams;
  if (vue && viewNames[vue]) return <ComingSection title={viewNames[vue]} />;
  return <div className="space-y-4"><div><p className="text-xs uppercase tracking-[.16em] text-race-primary">Saison 2026</p><h2 className="mt-1 text-xl font-semibold">Compétition</h2></div><CompetitionCard /><div className="grid gap-4 xl:grid-cols-[1.1fr_.9fr]"><section className="race-card rounded-2xl p-4 sm:p-5"><div className="flex items-center justify-between"><h3 className="font-semibold">Informations</h3><Radio className="size-5 text-race-success" /></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Info icon={MapPin} label="Lieu" value="Lac de barrage, Rabat" /><Info icon={CalendarDays} label="Dates" value="15–18 mai 2026" /><Info icon={Flag} label="Épreuves" value="12 catégories" /><Info icon={Trophy} label="Format" value="Qualifications & finales" /></div><div className="mt-5 grid grid-cols-3 gap-2"><Link href="/programme" className="rounded-xl bg-race-primary/10 p-3 text-center text-xs font-medium text-race-primary">Programme</Link><Link href="/resultats" className="rounded-xl bg-race-primary/10 p-3 text-center text-xs font-medium text-race-primary">Résultats</Link><Link href="/classements" className="rounded-xl bg-race-primary/10 p-3 text-center text-xs font-medium text-race-primary">Classements</Link></div></section><section className="race-card rounded-2xl p-4 sm:p-5"><div className="flex items-center justify-between"><h3 className="font-semibold">Prochaines courses</h3><Link href="/programme" className="text-[10px] text-race-primary">Tout voir</Link></div><div className="mt-3 space-y-2">{previewProgramme.slice(1, 4).map((race) => <Link href={race.status === "EN COURS" ? "/depart" : "/programme"} key={race.time} className="grid grid-cols-[48px_1fr_auto] items-center gap-2 rounded-xl border border-white/[0.06] p-3"><b className="text-xs">{race.time}</b><span className="truncate text-[11px]">{race.name}</span><ChevronRight className="size-4 text-race-muted" /></Link>)}</div></section></div><section className="race-card rounded-2xl p-4 sm:p-5"><div className="flex items-center justify-between"><h3 className="font-semibold">Classement des clubs</h3><Link href="/classements" className="text-[10px] text-race-primary">Classement complet</Link></div><div className="mt-3 divide-y divide-white/[0.06]">{previewClubRankings.slice(0, 3).map((item) => <div key={item.club} className="grid grid-cols-[30px_1fr_auto] py-3 text-xs"><b className="text-race-warning">{item.rank}</b><span>{item.club}</span><b>{item.points} pts</b></div>)}</div></section></div>;
}

function Info({ icon: Icon, label, value }: { icon: typeof MapPin; label: string; value: string }) { return <div className="rounded-xl border border-white/[0.06] bg-black/10 p-3"><Icon className="size-4 text-race-primary" /><p className="mt-2 text-[9px] uppercase text-race-muted">{label}</p><p className="mt-1 text-xs font-medium">{value}</p></div>; }
function ComingSection({ title }: { title: string }) { return <section className="race-card mx-auto max-w-3xl rounded-2xl p-7"><Flag className="size-7 text-race-primary" /><h2 className="mt-5 text-2xl font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-race-muted">Cette section est reliée au parcours compétition. Les données réelles seront chargées depuis Firebase après validation des règles et des permissions.</p><Link href="/competitions" className="mt-6 inline-flex rounded-xl bg-race-primary px-4 py-3 text-sm font-semibold">Retour à la compétition</Link></section>; }
